version: '3'

services:
  rabbitmq1:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - RABBITMQ_ERLANG_COOKIE=f74b11254454825e841847cbb9b20395c5d3be55fa8cda1545d8a63afdc6d362
      - RABBITMQ_DEFAULT_VHOST=/vhost1
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - jibe-app-network

  back-end-app:
    build:
      context: backend/
      dockerfile: Dockerfile
    environment:
      - APP_PORT=3001
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq1:5672//vhost1
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_USER=jibe
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=mypsdb
    ports:
      - "3001:3001"
    networks:
      - jibe-app-network

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: jibe
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: mypsdb
    ports:
      - "5432:5432"
    networks:
        - jibe-app-network

  front-end:
    build:
      context: frontend/
      dockerfile: Dockerfile
    environment:
      - PORT=80
      - ROOT_API_URL=http://backend-app:3001/api
    ports:
      - "3000:80"
    networks:
      - jibe-app-network

networks:
  jibe-app-network:
    driver: bridge
    external: true
